package com.bawei.wuruitao.greeendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.wuruitao.model.entity.CategoryBean;

import com.bawei.wuruitao.greeendao.CategoryBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryBeanDaoConfig;

    private final CategoryBeanDao categoryBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryBeanDaoConfig = daoConfigMap.get(CategoryBeanDao.class).clone();
        categoryBeanDaoConfig.initIdentityScope(type);

        categoryBeanDao = new CategoryBeanDao(categoryBeanDaoConfig, this);

        registerDao(CategoryBean.class, categoryBeanDao);
    }
    
    public void clear() {
        categoryBeanDaoConfig.clearIdentityScope();
    }

    public CategoryBeanDao getCategoryBeanDao() {
        return categoryBeanDao;
    }

}
